CREATE TABLE T1 
(
   P INT,
   Q VARCHAR(1),
   R INT
);

CREATE TABLE T2 
(
   A INT,
   B VARCHAR(1),
   R INT
);

INSERT INTO T1 VALUES 
(10, 'a', 5),
(15, 'b', 8),
(25, 'a', 6);

INSERT INTO T2 VALUES 
(10, 'b', 6),
(25, 'c', 3),
(10, 'b', 5);

SELECT * FROM T1 JOIN T2 ON T1.P = T2.A;
SELECT * FROM T1 JOIN T2 ON T1.Q = T2.B;
SELECT * FROM T1 LEFT JOIN T2 ON T1.P = T2.A;
SELECT * FROM T1 RIGHT JOIN T2 ON T1.Q = T2.B;
SELECT * FROM T1 UNION SELECT * FROM T2;
SELECT * FROM T1 JOIN T2 ON (T1.P = T2.A AND T1.R = T2.C)
